modules/admin/controllers/RatingConfigsController.php
<?php

namespace app\modules\admin\controllers;

use app\models\RatingConfigForms\Report;
use app\models\RatingConfigForms\Group;
use app\models\RatingConfigForms\Rater;
use app\models\RatingConfigForms\Items;
use app\models\Answers;
use app\models\RatingConfigForms\Units;
use Yii;

use app\models\Projects;
use app\models\RatingConfigs;
use app\models\Raters;


use yii\data\ArrayDataProvider;
use yii\data\ActiveDataProvider;
use app\modules\admin\controllers\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

use yii\helpers\Url;

/**
 * RatingConfigsController implements the CRUD actions for RatingConfigs model.
 */
class RatingConfigsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all RatingConfigs models.
     * @return mixed
     */
    public function actionIndex($projectID)
    {
        $this->layout = '@app/modules/admin/views/layout/columns2';
        
        Yii::$app->session->set('projectID', $projectID);
        Yii::$app->session->set('projectName', Projects::getName($projectID));
        
        
        
        $dataProvider = new ActiveDataProvider([
            'query' => RatingConfigs::find()->where(['projectID' => $projectID]),
        ]);

        return $this->render('index', [
            'projectID' => $projectID,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single RatingConfigs model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $this->layout = '@app/modules/admin/views/layout/columns2';
        
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new RatingConfigs model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new RatingConfigs;
        $model->projectID = Yii::$app->request->get('projectID');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index','projectID'=>$model->projectID]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing RatingConfigs model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing RatingConfigs model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $projectID = $model->projectID;
        $model->delete();
        self::flash('warning', 'Rating Set Configutation Deleted!');
        
        return $this->redirect(['index','projectID'=>$projectID]);
    }

    // *** Rating Structure ****
    public function actionItems($rcID)
    {
        $data = [];
        $rcModel = $this->findModel($rcID);
        $req = Yii::$app->request;
        
        $itemM = new Items($rcID);

        //Delete
        if ($req->post('action') == 'delete') {
            $itemM->key = $req->post('itemKey');
            $itemM->delete();
            $this->flash("success", "Item has been deleted");
            return $this->redirect(['items','rcID'=>$rcID]);
        }
        
        //Update
        if ($req->get('action')=='update') {
            $itemKey = $req->get('itemKey');
            $item_ = $rcModel->getItems()[$itemKey];
            $itemM->attributes = $item_;
            $itemM->key = $itemKey;
        }
        
        //Update | New
        if ($req->post('action')=='save') {
            if ($itemM->load($req->post()) && $itemM->save()) {
                $this->flash("success", "Item has successfully added / updated.");
                return $this->redirect(['items','rcID'=>$rcID]);
            }
        }

        $data['itemM'] = $itemM;
        $data['rcModel'] = $rcModel;
        $data['items'] = $rcModel->getItems();
                
        return $this->render('items', $data);
    }
    
    //displays image data
    public function actionItemImage($rcID, $itemID)
    {
        $rcModel = $this->findModel($rcID);
        $model = new Items($rcID, $rcModel);
        $itemObj = $model->findOne($itemID);
        $path = Url::to('@webroot') .'/'.$itemObj->question;
        
        $response = \Yii::$app->response;
        $response->format = Response::FORMAT_RAW;
        $response->headers->add('content-type', 'image/png');
        $img_data = file_get_contents($path);
        $response->data = $img_data;
        return $response;
    }

    public function actionUnits($rcID)
    {
        $postData = Yii::$app->request->post();
        $action = Yii::$app->request->get("action");
        $id = Yii::$app->request->get("id");
        $rcModel = $this->findModel($rcID);

        if (!empty($postData)) {
            if ($postData['name'] !='') {
                $rcModel->saveUnits($postData);
                self::flash('success', "Unit added successfuly");
            } else {
                self::flash('error', "Unit name can not be empty");
            }
        } elseif ($action == 'delete' && $id!='') {
            $rcModel->deleteUnit($id);
            self::flash('warning', "Unit Deleted");
            return $this->redirect(['units','rcID'=>$rcID]);
        }

        $unitsA = $rcModel->getUnits();
        $maxKey = (count($unitsA)>0) ? max(array_keys($unitsA)) + 1 : 0;
        $maxKey = $maxKey + 1;
        
        
        return $this->render(
                    'units',
                    [
                        'list'=>$unitsA,
                        'rcID'=>$rcID,
                        'rcM' => $rcModel,
                        'maxKey' => $maxKey
                    ]
                );
    }
    
        
    public function actionAssignItemToUnit($rcID)
    {
        $rcModel = $this->findModel($rcID);

        $action = Yii::$app->request->post("action");
        $unitKey= Yii::$app->request->post("unitKey");
        $itemKey= Yii::$app->request->post("itemKey");

        if ($action=="up") {
            $rcModel->unitUp($unitKey);
        } elseif ($action=="down") {
            $rcModel->unitDown($unitKey);
        } elseif ($action=="delete") {
            $rcModel->deleteUnit($unitKey);
        } elseif ($action=="assignItem") {
            if ($rcModel->assignItemToUnit($itemKey, $unitKey)) {
                self::flash('success', "Item successfuly assigned.");
            } else {
                self::flash('danger', implode("", $group->getErrors("rating_units")));
            }
            return $this->redirect(['assign-item-to-unit','rcID'=>$rcID]);
        } elseif ($action=="unassignItem") {
            if ($rcModel->unassignItemFromUnit($itemKey, $unitKey)) {
                self::flash('success', "Item successfuly unassigned.");
            } else {
                self::flash('danger', implode("", $group->getErrors("rating_units")));
            }
            return $this->redirect(['assign-item-to-unit','rcID'=>$rcID]);
        }
        // items
        $items = $rcModel->getItems();
        // units
        $units = $rcModel->getUnits();

        return $this->render('assignItemToUnit', [
            'rcID' => $rcID,
            'items'=> $items,
            'units'=> $units,
        ]);
    }

    public function actionBlocks($rcID)
    {
        $action = Yii::$app->request->post("action");
        $rcModel = $this->findModel($rcID);


        if ($action=="addBlock") {
            $data = Yii::$app->request->post();
            if ($data["name"] != '') {
                $rcModel->saveBlock($data);
                self::flash('success', "Block added successfuly");
                return $this->redirect(['blocks','rcID'=>$rcID]);
            } else {
                self::flash('error', "Block name can not be empty");
            }
        } elseif ($action=="up") {
            $blockKey= Yii::$app->request->post("blockKey");
            $rcModel->blockUp($blockKey);
        } elseif ($action=="down") {
            $blockKey= Yii::$app->request->post("blockKey");
            $rcModel->blockDown($blockKey);
        } elseif ($action=="delete") {
            $blockKey= Yii::$app->request->post("blockKey");
            $rcModel->deleteBlock($blockKey);
        }


        return $this->render('blocks', ['model'=>$rcModel]);
    }
    
    
    public function actionBlockSettings($rcID, $blockKey)
    {
        $rcModel = $this->findModel($rcID);
        $blockSettingsModel = new \app\models\RatingConfigForms\BlockSettings($rcModel, $blockKey);
        
        $action = Yii::$app->request->post("action");

        if ($action=="save") {
            $postData = Yii::$app->request->post();
            if ($blockSettingsModel->load($postData) && $blockSettingsModel->save()) {
                self::flash('success', 'Block Settings successfully saved.');
            }
        } elseif ($action=="assignGroup") {

modules/admin/views/rating-configs/assignItemToUnit.php
<?php
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
use yii\helpers\Html;

$this->title = "Assign Items To Unit";

$rcModel = \app\models\RatingConfigs::findOne($rcID);

$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['projects/']];
$this->params['breadcrumbs'][] = ['label' => 'Test Sets', 'url' => ['index', 'projectID' => $rcModel->projectID]];
$this->params['breadcrumbs'][] = ['label'=> $rcModel->test_name, 'url'=>['rating-configs/view','id'=>$rcID]];
$this->params['breadcrumbs'][] = $this->title;

function deleteLink($key)
{
    return Html::a(
        '<i class="fa fa-minus-circle"></i>',
        ['assign-item-to-unit', 'rcID'=>Yii::$app->request->get('rcID')],
        ["data-confirm"=>"Are you sure want to delete this unit?", "data-method"=>"post", "data-params"=>['action'=>'delete', 'unitKey'=>$key]]
    );
}

function updownLink($key, $list)
{
    $s = '';

    if ($key != 0) {
        $s = Html::a(
            '<i class="fa fa-arrow-up block-arrow" style="color:green"></i>',
            ['assign-item-to-unit', 'rcID'=>Yii::$app->request->get('rcID')],
            ["data-method"=>"post", "data-params"=>['action'=>'up', 'unitKey'=>$key]]
        );
    }

    if ($key!=count($list)-1) {
        $s .= Html::a(
            '<i class="fa fa-arrow-down block-arrow" style="color:green;"></i>',
            ['assign-item-to-unit', 'rcID'=>Yii::$app->request->get('rcID')],
            ["data-method"=>"post", "data-params"=>['action'=>'down', 'unitKey'=>$key]]
        );
    }
    return "<span class='updownLink'>{$s}</span>";
}

function showForm($view, $units, $key, $items)
{
    if (Yii::$app->request->get("forms")=="addUnit") {
        return $view->render('forms/_addUnit', ["key"=>$key]);
    } elseif (Yii::$app->request->get("forms")=="assignItemToUnit") {
        return $view->render('forms/_assignItemToUnit', ["items" => $items, "unit" => $units[$key], "unitKey"=>$key]);
    }
}

function fa($icon='', $url=[], $opts = [])
{
    switch ($icon) {

        case 'edit':
            $i = "<i class='fa fa-edit'> </i>";
            break;
        case 'trash':
            $i = "<i class='fa fa-trash-o'> </i>";
            break;
        case 'create':
            $i = "<i class='fa fa-plus'> </i>";
            break;
        default:
            $i = "<i class='fa fa-$icon'> </i>";
            break;
    }
    if (count($url)) {
        return Html::a($i, $url, $opts);
    } else {
        return $i;
    }
}

$css = <<<CSS
i {
	padding-right: 4px;
}
.block-div {
	padding: 10px;
}

.block-name {
	display:inline-block;
	padding: 0 10px;
	font-size: 20px;	
}

.block-arrow {
	margin-right:5px;
}

.group-div {
	padding:10px 50px;
}

.group-item-div {
	padding: 10px 20px;
}

.group-qfy-div {
	padding: 5px 30px;
}
.group-qfy-div li {
	font-size: 12px;
}

.updownLink {
	display: inline-block;
	width: 60px;

}

.displayhide{
    display: none;
}

CSS;

$this->registerCss($css);

$items = $rcModel->getItems();
$unitID = Yii::$app->request->get("unitID");
$unitKey = Yii::$app->request->get("unitKey");


?>

<h1>Assign Items To Unit</h1>

<p>
	<?= Html::a('Back', ['view','id'=>$rcID], ['class'=>'btn btn-default']) ?>
</p>


<div class="row">

<?php Pjax::begin(["scrollTo"=>200]); ?>

<div class="col-md-6">
	<div class="panel panel-default">
		<div class="panel-heading">Unit Structures</div>

        <div class="panel-body">
            <?php if (count($units)):
                foreach ($units as $idx => $item) {
                    echo $this->render('blocks/_listUnit', ["rcModel"=>$rcModel, "unitKey"=>$idx, "units"=>$units, 'items' => $items]);
                } else:
                ?>
                <div class="block-div">
                    <div class='alert alert-warning'>
                        No units found.
                    </div>
                    <?=Html::a(fa('plus-circle').' Add unit', ['units', "rcID"=>$rcID, "forms"=>"addUnit", "id"=>0], ["class"=>"btn btn-default"]); ?>
                    <hr>
                </div>
                <?php
            endif; ?>
        </div>
	</div>
</div>

    <div class="col-md-4">
        <?=showForm($this, $units, $unitKey, $items)?>
    </div>
<?php Pjax::end(); ?>
</div>

<div class="div-space"></div>

modules/admin/views/rating-configs/block-settings.php
<?php 
use app\components\Icon;
use app\models\Raters;
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;

$this->title = "Block Settings #{$model->blockKey}";

$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['projects/']];
$this->params['breadcrumbs'][] = ['label' => 'Test Sets', 'url' => ['index', 'projectID' => $rcModel->projectID]];
$this->params['breadcrumbs'][] = ['label'=> $rcModel->test_name, 'url'=>['rating-configs/view','id'=>$rcModel->id]];
$this->params['breadcrumbs'][] = ['label'=> 'Rating Blocks', 'url'=>['rating-configs/blocks','rcID'=>$rcModel->id, "groups"=>1]];
$this->params['breadcrumbs'][] = $this->title;

function showAssignedGroups($rcGroups, $blockKey, $rcModel)
{
    $htmlResult = "";
    if (isset($rcGroups[$blockKey]) &&
        is_array($rcGroups[$blockKey])) {
        $number = 1;
        $groupsA = Raters::getGroups();
        foreach ($rcGroups[$blockKey] as $rcGroup) {
            $gid = $rcGroup["gID"];
            $totalRater = Raters::assignedRaterCount($rcGroup["gID"]);
            $qualifiedRater = $rcModel->getGroupRatersStatusCount($blockKey, $rcGroup["gID"], "ok");
            $unQualifiedRater = $totalRater - $qualifiedRater;
            $htmlResult .=" <tr>
                                <td>".$number."</td>
                                <td>".$groupsA[$gid]["name"]."</td>
                                <td>".$qualifiedRater."</td>
                                <td>".$unQualifiedRater."</td>
                                <td>".
                                    Icon::fa(
                                        'edit',
                                        [
                                            'block-raters',
                                            'rcID'=>$rcModel->id,
                                            'blockKey'=>$blockKey,
                                            'groupID'=>$gid
                                        ],
                                        [
                                            "data-pjax"=>0
                                        ]
                                    )." ".
                                    Icon::fa(
                                        'delete',
                                        [
                                            'block-settings',
                                            'rcID'=>$rcModel->id,
                                            'blockKey'=>$blockKey
                                        ],
                                        [
                                            "data-confirm"=>"Are you sure want to remove this group from block?",
                                            "data-method"=>"post",
                                            "data-params"=>[
                                                'action'=>'unassignGroup',
                                                'blockKey'=>$blockKey,
                                                "gID"=>$gid
                                            ]
                                        ]
                                    )."</td>
                            </tr>";
            $number++;
        }
    }

    return $htmlResult;
}

function showUnAssignedGroups($blockKey, $rcModel)
{
    $htmlResult = "";
    $assignedGroup = ArrayHelper::getColumn($rcModel->getGroups($blockKey), "gID");
    $groupsA = Raters::getGroups();
    $groupMap = [];
    $number = 1;
    foreach ($groupsA as $group) {
        if (!in_array($group["code"], $assignedGroup)) {
            $htmlResult .= "<tr>
                                <td>".$number."</td>
                                <td>".$group["name"]."</td>
                                <td>".
                                    Icon::Fa(
                                        'add',
                                        [
                                            "block-settings",
                                            "rcID" => $rcModel->id,
                                            "blockKey" => $blockKey
                                        ],
                                        [
                                            "data-method"=> "post",
                                            "data-params"=>[
                                                "action" => "assignGroup",
                                                "blockKey" => $blockKey,
                                                "gID" => $group["code"]
                                            ]
                                        ]
                                    ).
                                "</td>
                            </tr>";
            $number++;
        }
    }
    return $htmlResult;
}

$css = <<<CSS
.div-section{
    padding-left:22px;
}
CSS;

$this->registerCSS($css);

$blockKey = Yii::$app->request->get('blockKey');
$rcGroups = $rcModel->getGroups();
$assignedGroupsCount = isset($rcGroups[$blockKey]) ? count($rcGroups[$blockKey]) : 0;

?>
 
 
<div class="block-settings">

    <h1><?= $this->title ?></h1>
    <p>
        <?=
            Html::a(
                'Back',
                [
                    'blocks',
                    'rcID'=>$rcModel->id,
                    "groups"=>1
                ],
                [
                    'class'=>'btn btn-default'
                ]
            )
        ?>
    </p>
	
	
	<section>
	
	<h3> General RAB Settings </h3>
    <div class="row">
        <div class="col-md-8">

                <?php 
                    $form = ActiveForm::begin(
                                [
                                    "options"=> [
                                        "class"=>"form-horizontal",
                                    ],
                                    "fieldConfig"=>[
                                        "template"=> "{label}\n<div class=\"col-sm-3\">{input}</div>\n{hint}\n{error}",
                                        "labelOptions"=> [
                                            "class"=>"col-sm-3"
                                        ],
                                        "inputOptions"=>[
                                            "class"=>"form-control",
                                            "size" => 5
                                        ]
                                    ]
                                ]
                            );
                ?>
                    <?=Html::hiddenInput("action", "save")?>

                    <h4><?=Icon::fa("cog")?> Training</h4>

                    <div class="div-section">

                        <?= $form->field($model, 'hasTraining')->radioList(
                            ["1"=>'Yes', "0"=>'No'],
                            [
                                "itemOptions"=> [
                                    "labelOptions" => [
                                        "class" => "col-sm-6",
                                    ]
                                ]
                            ]
                        ) ?>

                        <?= $form->field($model, 'fEveryday')->textInput() ?>

                        <?= $form->field($model, 'afterBlocks')->textInput() ?>

                        <?= $form->field($model, 'dayLimit')->textInput() ?>

                        <?= $form->field($model, 'afterDays')->textInput() ?>

                    </div>

                    <h4><?=Icon::fa("cog")?> Quality Control</h4>
                    <div class="div-section">

                        <?= $form->field($model, 'qcLimit')->textInput() ?>
                        
                    </div>

                    <div class="div-section">
                        <div class="form-group">
                            <div class="col-sm-3"></div>
                            <div class="col-sm-6">
                                <?= Html::submitButton("Save", ["class"=>"btn btn-primary"])?>
                            </div>
                        </div>
                    </div>

            	<?php ActiveForm::end() ?>

        </div>


        <div class="col-md-4">

        </div>

    </div>

	</section>
	
	<section>
		<h3>Add Group To Block</h3>
		
		<div class="row">
		<div class="col-md-6">
			<div class="panel panel-default">
				<div class="panel-heading">
					Groups in Block (<?=$assignedGroupsCount?>)
				</div>
				<div class="panel-body">
					<table class="table table-bordered">
						<tr>
							<th>ID</th>
							<th>Group Name</th>
                            <th>Qualified</th>
                            <th>Unqualified</th>
							<th>Options</th>
						</tr>
                        <?=showAssignedGroups($rcGroups, $blockKey, $rcModel)?>
					</table>
				</div>
			</div>
		</div>
		

		<div class="col-md-6">
			<div class="panel panel-primary">
				<div class="panel-heading">
					Available Group in Project
				</div>
						<div class="panel-body">
					<table class="table table-bordered">
						<tr>
							<th>ID</th>
							<th>Group Name</th>
							<th>Options</th>
						</tr>
                        <?=showUnAssignedGroups($blockKey, $rcModel)?>
					</table>
				</div>
			
			</div>
		</div>
		
		</div>
	</section>	
	
	
	
</div> 

modules/admin/views/rating-configs/blockRaters.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use app\models\Raters;
use app\models\RatingConfigForms\Rater;
use app\components\Icon;

/** @var \app\models\RatingConfigs $rcModel */

$this->title = "Test: ".$rcModel->test_name." Block: ".$block['name']." Group: ".$group['name'];

$this->params['breadcrumbs'][] = ['label' => 'Projects', 'url' => ['projects/']];
$this->params['breadcrumbs'][] = ['label' => 'Test Sets', 'url' => ['index', 'projectID' => $rcModel->projectID]];
$this->params['breadcrumbs'][] = ['label'=> $rcModel->test_name, 'url'=>['rating-configs/view','id'=>$rcModel->id]];
$this->params['breadcrumbs'][] = ['label'=> 'Rating Blocks', 'url'=>['rating-configs/blocks','rcID'=>$rcModel->id, "groups"=>1]];
$this->params['breadcrumbs'][] = [
                                    'label'=> 'Block Settings #'.$block["id"],
                                    'url'=>[
                                        'rating-configs/block-settings',
                                        'rcID'=>$rcModel->id,
                                        "blockKey"=>Yii::$app->request->get("blockKey")
                                    ]
                                ];
$this->params['breadcrumbs'][] = "Assign Rater to Block";


// count qualified, failed, dna member
$totalRater = Raters::assignedRaterCount($group["code"]);
$qualifiedRater = 0;
$failedRater = 0;
$dnaRater = 0;

$groupMembers = $dataProvider->query->all();
foreach ($groupMembers as $member) {
    $status = $rcModel->getRaterStatus($block["id"], $member->id);
    if ($status=="ok") {
        $qualifiedRater++;
    } elseif ($status=="fail") {
        $failedRater++;
    } elseif ($status=="dna") {
        $dnaRater++;
    }
}

$blockKey = Yii::$app->request->get("blockKey");
?>

<h1><?= $this->title ?></h1>
<p>
	<?=
        Html::a(
            'Back',
            [
                'block-settings',
                'rcID'=>$rcModel->id,
                "blockKey"=>$blockKey
            ],
            [
                'class'=>'btn btn-default'
            ]
        )
    ?>
</p>

<div class="row">
	<div class="col-md-3">
	<div class="panel panel-default">
		<div class="panel-body">
		Total Member: <?=$totalRater?>
		</div>

	</div>
	</div>
	<div class="col-md-3">
	<div class="panel panel-default">
		<div class="panel-body">
		Qualified: <?=$qualifiedRater?>
		</div>
	</div>
	</div>
	<div class="col-md-3">
	<div class="panel panel-default">
		<div class="panel-body">
		Failed: <?=$failedRater?>
		</div>
	</div>
	</div>

	<div class="col-md-3">
	<div class="panel panel-default">
		<div class="panel-body">
		Did Not Attempt: <?=$dnaRater?>
		</div>
	</div>
	</div>
</div>

<hr>

<div class="" style='padding: 10px 0'>
<?=
    Html::beginForm(
        [
            "block-raters",
            "rcID"=>$rcModel->id,
            "blockKey"=>$blockKey,
            "groupID"=>$group["code"]
        ],
        "get",
        [
            "class"=>'form-inline'
        ]
    )
?>
	<?=
        Html::textInput(
            'search_name',
            Yii::$app->request->get('search_name'),
            [
                'class'=>'form-control',
                'placeholder'=>'Name'
            ]
        );
    ?>
	<?=
        Html::dropDownList(
            'search_status',
            Yii::$app->request->get('search_status'),
            Rater::raterStatus(),
            [
                'class'=>'form-control',
                'prompt'=>'All Status'
            ]
        );
    ?>
	<?= Html::submitButton("Search", ["class"=>'btn btn-primary']); ?>
	
	<?php // ??? use model search object?>
	
<?=Html::endForm()?>
</div>

<div class="row">
    <?php Pjax::begin(["scrollTo"=>200]); ?>
		<div class="col-md-8">
			<?= GridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
                    'name',
                    [
                        'attribute' => 'status',
                        'value' => function ($model) use ($blockKey, $rcModel) {
                            $status = $rcModel->getRaterStatus($blockKey, $model->id);
                            return Rater::raterStatus($status);
                        }
                    ],
                    [
                        'attribute' => 'isLeader',
                        'label' => 'Leader',
                        'value' => function ($model) use ($blockKey, $rcModel) {
                            $isLeader = $rcModel->isLeaderRater($blockKey, $model->id);
                            return $isLeader ? Icon::fa('check') : Icon::fa('times');
                        },
                        'format'=>'html'
                    ],
                    [
                         'value'=> function ($model) use ($blockKey, $group, $rcModel) {
                             $btn = "<i class='fa fa-edit'></i> ";
                             return Html::a(
                                            $btn,
                                            [
                                                'block-raters',
                                                'raterID'=>$model->id,
                                                "edit"=>"assignRaterToBlock",
                                                "rcID"=>$rcModel->id,
                                                "blockKey"=>$blockKey,
                                                "groupID"=>$group["code"]
                                            ]
                                        );
                         },
                         'format'=>'html',
                    ],
                ]
            ]);?>
		</div>
		<div class="col-md-4">
			<?php
                if (Yii::$app->request->get("edit")=="assignRaterToBlock") {
                    $raterID = Yii::$app->request->get("raterID");
                    echo $this->render(
                            "forms/_assignRaterToBlock",
                            [
                                "raterID"=>$raterID,
                                "rcModel"=>$rcModel,
                                "block"=>$block,
                                "blockKey"=> $blockKey,
                                "group"=>$group
                            ]
                        );
                }
            ?>
		</div>
    <?php Pjax::end(); ?>	
</div>

modules/admin/views/rating-configs/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $projectID int */

$this->params['breadcrumbs'][] = ['label'=>'Projects','url'=>['projects/']];
$this->title = Yii::$app->session->get('projectName') . ' - Test Sets';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="rating-configs-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>

		<?= Html::a('Back',['projects/'],['class'=>'btn btn-default']) ?>
		<?= Html::a('Create Test Set',['rating-configs/create',
										'projectID'=>Yii::$app->request->get('projectID')]
									 ,['class'=>'btn btn-success'])
		?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [

            'id',
            ['attribute'=>'test_name',
			 'value'=> function ($model) {
						return Html::a($model->test_name,['view','id'=>$model->id]);
						},
			 'format'=>'html'
			],
			
            'date_updated:date',
			'Status',
	
			['label'=>'',
			'value'=>function($model) {
						$s = '';
						#$s .= Html::a('Manage',['view','id'=>$model->id],
						#						['class'=>'btn btn-xs btn-default']);
						#$s .= " ";
						$fa_report = "<i class='fa fa-line-chart'></i> ";
						$s .= Html::a($fa_report .'Report',['report','rcID'=>$model->id],
												['class'=>'btn btn-xs btn-warning']);
				return $s;
			},
			'format'=>'html'
			]
        ],
    ]); ?>
</div>